
var b;b||(b=typeof Module !== 'undefined' ? Module : {});var n={},t;for(t in b)b.hasOwnProperty(t)&&(n[t]=b[t]);var u=[],v="./this.program";function w(a,c){throw c;}var x=!1,y=!1,A=!1,ba=!1;x="object"===typeof window;y="function"===typeof importScripts;A="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ba=!x&&!A&&!y;var D="",E,F,G,H;
if(A)D=y?require("path").dirname(D)+"/":__dirname+"/",E=function(a,c){G||(G=require("fs"));H||(H=require("path"));a=H.normalize(a);return G.readFileSync(a,c?null:"utf8")},F=function(a){a=E(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(v=process.argv[1].replace(/\\/g,"/")),u=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=b),process.on("uncaughtException",function(a){if(!(a instanceof I))throw a;}),process.on("unhandledRejection",J),w=function(a){process.exit(a)},
b.inspect=function(){return"[Emscripten Module object]"};else if(ba)"undefined"!=typeof read&&(E=function(a){return read(a)}),F=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?u=scriptArgs:"undefined"!=typeof arguments&&(u=arguments),"function"===typeof quit&&(w=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(x||y)y?D=self.location.href:"undefined"!==typeof document&&document.currentScript&&(D=document.currentScript.src),D=0!==D.indexOf("blob:")?D.substr(0,D.lastIndexOf("/")+1):"",E=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},y&&(F=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});
var ca=b.print||console.log.bind(console),K=b.printErr||console.warn.bind(console);for(t in n)n.hasOwnProperty(t)&&(b[t]=n[t]);n=null;b.arguments&&(u=b.arguments);b.thisProgram&&(v=b.thisProgram);b.quit&&(w=b.quit);var L;b.wasmBinary&&(L=b.wasmBinary);var noExitRuntime;b.noExitRuntime&&(noExitRuntime=b.noExitRuntime);"object"!==typeof WebAssembly&&J("no native wasm support detected");var M,N=!1;function assert(a,c){a||J("Assertion failed: "+c)}
function da(){var a=b.__sargs_add_kvp;assert(a,"Cannot call unknown function _sargs_add_kvp, make sure it is exported");return a}function ea(a){var c=["string","string"],d={string:function(h){var m=0;if(null!==h&&void 0!==h&&0!==h){var B=(h.length<<2)+1;m=O(B);fa(h,P,m,B)}return m},array:function(h){var m=O(h.length);Q.set(h,m);return m}},f=da(),g=[],e=0;if(a)for(var k=0;k<a.length;k++){var p=d[c[k]];p?(0===e&&(e=ha()),g[k]=p(a[k])):g[k]=a[k]}f.apply(null,g);0!==e&&ia(e)}
var ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;function fa(a,c,d,f){if(0<f){f=d+f-1;for(var g=0;g<a.length;++g){var e=a.charCodeAt(g);if(55296<=e&&57343>=e){var k=a.charCodeAt(++g);e=65536+((e&1023)<<10)|k&1023}if(127>=e){if(d>=f)break;c[d++]=e}else{if(2047>=e){if(d+1>=f)break;c[d++]=192|e>>6}else{if(65535>=e){if(d+2>=f)break;c[d++]=224|e>>12}else{if(d+3>=f)break;c[d++]=240|e>>18;c[d++]=128|e>>12&63}c[d++]=128|e>>6&63}c[d++]=128|e&63}}c[d]=0}}
function ka(a){for(var c=0,d=0;d<a.length;++d){var f=a.charCodeAt(d);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++d)&1023);127>=f?++c:c=2047>=f?c+2:65535>=f?c+3:c+4}c+=1;d=O(c);fa(a,Q,d,c);return d}var la,Q,P,R;function ma(){var a=M.buffer;la=a;b.HEAP8=Q=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=R=new Int32Array(a);b.HEAPU8=P=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}
var S,na=[],oa=[],pa=[],qa=[];function ra(){var a=b.preRun.shift();na.unshift(a)}var T=0,U=null,V=null;b.preloadedImages={};b.preloadedAudios={};function J(a){if(b.onAbort)b.onAbort(a);K(a);N=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function W(a){var c=X;return String.prototype.startsWith?c.startsWith(a):0===c.indexOf(a)}function sa(){return W("data:application/octet-stream;base64,")}var X="sokol-test.wasm";
if(!sa()){var ua=X;X=b.locateFile?b.locateFile(ua,D):D+ua}function va(){var a=X;try{if(a==X&&L)return new Uint8Array(L);if(F)return F(a);throw"both async and sync fetching of the wasm failed";}catch(c){J(c)}}function wa(){return L||!x&&!y||"function"!==typeof fetch||W("file://")?Promise.resolve().then(function(){return va()}):fetch(X,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+X+"'";return a.arrayBuffer()}).catch(function(){return va()})}
function Y(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var d=c.v;"number"===typeof d?void 0===c.u?S.get(d)():S.get(d)(c.u):d(void 0===c.u?null:c.u)}}}var xa=[null,[],[]],ya={};oa.push({v:function(){za()}});
var Aa={f:function(){return 0},g:function(){},c:function(a,c,d){P.copyWithin(a,c,c+d)},d:function(a){a>>>=0;var c=P.length;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,a+100663296);f=Math.max(16777216,a,f);0<f%65536&&(f+=65536-f%65536);a:{try{M.grow(Math.min(2147483648,f)-la.byteLength+65535>>>16);ma();var g=1;break a}catch(e){}g=void 0}if(g)return!0}return!1},b:function(){return 0},i:function(a,c){a=1==a||2==a?2:J();Q[c>>0]=a;return 0},e:function(a,c,d,f){a=ya.B(a);
c=ya.A(a,c,d);R[f>>2]=c;return 0},h:function(){},a:function(a,c,d,f){for(var g=0,e=0;e<d;e++){for(var k=R[c+8*e>>2],p=R[c+(8*e+4)>>2],h=0;h<p;h++){var m=P[k+h],B=xa[a];if(0===m||10===m){m=1===a?ca:K;var q=B;for(var r=0,z=r+NaN,C=r;q[C]&&!(C>=z);)++C;if(16<C-r&&q.subarray&&ja)q=ja.decode(q.subarray(r,C));else{for(z="";r<C;){var l=q[r++];if(l&128){var aa=q[r++]&63;if(192==(l&224))z+=String.fromCharCode((l&31)<<6|aa);else{var ta=q[r++]&63;l=224==(l&240)?(l&15)<<12|aa<<6|ta:(l&7)<<18|aa<<12|ta<<6|q[r++]&
63;65536>l?z+=String.fromCharCode(l):(l-=65536,z+=String.fromCharCode(55296|l>>10,56320|l&1023))}}else z+=String.fromCharCode(l)}q=z}m(q);B.length=0}else B.push(m)}g+=p}R[f>>2]=g;return 0},j:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),c=a.next();!c.done;c=a.next())ea([c.value[0],c.value[1]])}};
(function(){function a(g){b.asm=g.exports;M=b.asm.k;ma();S=b.asm.l;T--;b.monitorRunDependencies&&b.monitorRunDependencies(T);0==T&&(null!==U&&(clearInterval(U),U=null),V&&(g=V,V=null,g()))}function c(g){a(g.instance)}function d(g){return wa().then(function(e){return WebAssembly.instantiate(e,f)}).then(g,function(e){K("failed to asynchronously prepare wasm: "+e);J(e)})}var f={a:Aa};T++;b.monitorRunDependencies&&b.monitorRunDependencies(T);if(b.instantiateWasm)try{return b.instantiateWasm(f,a)}catch(g){return K("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){return L||"function"!==typeof WebAssembly.instantiateStreaming||sa()||W("file://")||"function"!==typeof fetch?d(c):fetch(X,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,f).then(c,function(e){K("wasm streaming compile failed: "+e);K("falling back to ArrayBuffer instantiation");return d(c)})})})();return{}})();var za=b.___wasm_call_ctors=function(){return(za=b.___wasm_call_ctors=b.asm.m).apply(null,arguments)};
b.__sargs_add_kvp=function(){return(b.__sargs_add_kvp=b.asm.n).apply(null,arguments)};b.___em_js__sargs_js_parse_url=function(){return(b.___em_js__sargs_js_parse_url=b.asm.o).apply(null,arguments)};b._main=function(){return(b._main=b.asm.p).apply(null,arguments)};
var ha=b.stackSave=function(){return(ha=b.stackSave=b.asm.q).apply(null,arguments)},ia=b.stackRestore=function(){return(ia=b.stackRestore=b.asm.r).apply(null,arguments)},O=b.stackAlloc=function(){return(O=b.stackAlloc=b.asm.s).apply(null,arguments)},Z;function I(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}V=function Ba(){Z||Ca();Z||(V=Ba)};
function Ca(a){function c(){if(!Z&&(Z=!0,b.calledRun=!0,!N)){Y(oa);Y(pa);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(Da){var d=a,f=b._main;d=d||[];var g=d.length+1,e=O(4*(g+1));R[e>>2]=ka(v);for(var k=1;k<g;k++)R[(e>>2)+k]=ka(d[k-1]);R[(e>>2)+g]=0;try{var p=f(g,e);if(!noExitRuntime||0!==p){if(!noExitRuntime){if(b.onExit)b.onExit(p);N=!0}w(p,new I(p))}}catch(h){h instanceof I||("unwind"==h?noExitRuntime=!0:((d=h)&&"object"===typeof h&&h.stack&&(d=[h,h.stack]),K("exception thrown: "+d),w(1,
h)))}finally{}}if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)d=b.postRun.shift(),qa.unshift(d);Y(qa)}}a=a||u;if(!(0<T)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ra();Y(na);0<T||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);c()},1)):c())}}b.run=Ca;if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();
var Da=!0;b.noInitialRun&&(Da=!1);noExitRuntime=!0;Ca();
