#include "particle_js.h"
#include "particle_system.h"
#include "../runtime.h"
#include <string.h>

typedef struct { ParticleSystem *system; } JSParticle;
static JSClassID particle_class_id;
static int particle_class_ready;

static JSValue prop(JSContext*ctx,JSValueConst obj,const char*name){return JS_GetPropertyStr(ctx,obj,name);}
static int number(JSContext*ctx,JSValueConst obj,const char*name,float*out){JSValue v=prop(ctx,obj,name);int ok=!JS_IsUndefined(v)&&!JS_IsNull(v);double d;if(ok&&JS_ToFloat64(ctx,&d,v)<0){JS_FreeValue(ctx,v);return -1;}if(ok)*out=(float)d;JS_FreeValue(ctx,v);return ok;}
static int boolean(JSContext*ctx,JSValueConst obj,const char*name,int*out){JSValue v=prop(ctx,obj,name);int ok=!JS_IsUndefined(v)&&!JS_IsNull(v);if(ok){int b=JS_ToBool(ctx,v);if(b<0){JS_FreeValue(ctx,v);return -1;}*out=b;}JS_FreeValue(ctx,v);return ok;}
static int string_is(JSContext*ctx,JSValueConst obj,const char*name,const char*wanted){JSValue v=prop(ctx,obj,name);if(!JS_IsString(v)){JS_FreeValue(ctx,v);return 0;}const char*s=JS_ToCString(ctx,v);int yes=s&&!strcmp(s,wanted);if(s)JS_FreeCString(ctx,s);JS_FreeValue(ctx,v);return yes;}

static int array_length(JSContext*ctx,JSValueConst array,uint32_t*out){JSValue v=prop(ctx,array,"length");int r=JS_ToUint32(ctx,out,v);JS_FreeValue(ctx,v);return r;}
static int parse_curve(JSContext*ctx,JSValueConst array,ParticleCurve*c){uint32_t n=0;if(array_length(ctx,array,&n)<0)return -1;if(n>PARTICLE_CURVE_MAX_KEYS)n=PARTICLE_CURVE_MAX_KEYS;c->count=0;for(uint32_t i=0;i<n;i++){JSValue pair=JS_GetPropertyUint32(ctx,array,i);uint32_t pn=0;if(array_length(ctx,pair,&pn)<0||pn<2){JS_FreeValue(ctx,pair);return -1;}JSValue a=JS_GetPropertyUint32(ctx,pair,0),b=JS_GetPropertyUint32(ctx,pair,1);double x,y;int err=JS_ToFloat64(ctx,&x,a)|JS_ToFloat64(ctx,&y,b);JS_FreeValue(ctx,a);JS_FreeValue(ctx,b);JS_FreeValue(ctx,pair);if(err<0)return -1;if(i&&x<c->time[i-1])return -1;c->time[i]=(float)x;c->value[i]=(float)y;c->count++;}return c->count?0:-1;}
static int parse_value(JSContext*ctx,JSValueConst v,ParticleValue*out){
  if(JS_IsNumber(v)){double d;if(JS_ToFloat64(ctx,&d,v)<0)return -1;memset(out,0,sizeof(*out));out->type=PARTICLE_VALUE_CONSTANT;out->constant=(float)d;return 0;}
  if(JS_IsArray(ctx,v)){uint32_t n=0;if(array_length(ctx,v,&n)<0||n!=2)return -1;JSValue a=JS_GetPropertyUint32(ctx,v,0),b=JS_GetPropertyUint32(ctx,v,1);double x,y;int err=JS_ToFloat64(ctx,&x,a)|JS_ToFloat64(ctx,&y,b);JS_FreeValue(ctx,a);JS_FreeValue(ctx,b);if(err<0)return -1;memset(out,0,sizeof(*out));out->type=PARTICLE_VALUE_RANGE;out->range.min=(float)x;out->range.max=(float)y;if(out->range.min>out->range.max){float t=out->range.min;out->range.min=out->range.max;out->range.max=t;}return 0;}
  if(JS_IsObject(v)){JSValue curve=prop(ctx,v,"overLife");if(JS_IsArray(ctx,curve)){memset(out,0,sizeof(*out));out->type=PARTICLE_VALUE_CURVE;int r=parse_curve(ctx,curve,&out->curve);JS_FreeValue(ctx,curve);return r;}JS_FreeValue(ctx,curve);}
  return -1;
}
static int value_prop(JSContext*ctx,JSValueConst obj,const char*name,ParticleValue*out){JSValue v=prop(ctx,obj,name);if(JS_IsUndefined(v)||JS_IsNull(v)){JS_FreeValue(ctx,v);return 0;}int r=parse_value(ctx,v,out);JS_FreeValue(ctx,v);return r<0?-1:1;}
static int parse_size_prop(JSContext*ctx,JSValueConst obj,ParticleConfig*c){JSValue v=prop(ctx,obj,"size");if(JS_IsUndefined(v)||JS_IsNull(v)){JS_FreeValue(ctx,v);return 0;}if(JS_IsObject(v)){JSValue range=prop(ctx,v,"range");if(!JS_IsUndefined(range)&&!JS_IsNull(range)){if(parse_value(ctx,range,&c->size)<0){JS_FreeValue(ctx,range);JS_FreeValue(ctx,v);return -1;}JS_FreeValue(ctx,range);JSValue over=prop(ctx,v,"overLife");if(!JS_IsArray(ctx,over)){JS_FreeValue(ctx,over);JS_FreeValue(ctx,v);return -1;}memset(&c->size_over_life,0,sizeof(c->size_over_life));c->size_over_life.type=PARTICLE_VALUE_CURVE;int r=parse_curve(ctx,over,&c->size_over_life.curve);JS_FreeValue(ctx,over);JS_FreeValue(ctx,v);return r;}JS_FreeValue(ctx,range);}int r=parse_value(ctx,v,&c->size);JS_FreeValue(ctx,v);return r;}

static JSParticle* get(JSContext*ctx,JSValueConst self){JSParticle*w=JS_GetOpaque2(ctx,self,particle_class_id);if(w&&!w->system)JS_ThrowTypeError(ctx,"particle system has been destroyed");return w&&w->system?w:NULL;}
static JSValue noarg(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv,int magic){(void)argc;(void)argv;JSParticle*w=get(ctx,self);if(!w)return JS_EXCEPTION;switch(magic){case 0:particle_system_start(w->system);break;case 1:particle_system_stop(w->system);break;case 2:w->system->paused=1;break;case 3:w->system->paused=0;break;}return JS_UNDEFINED;}
static JSValue emit(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv){JSParticle*w=get(ctx,self);if(!w)return JS_EXCEPTION;int32_t n=1;if(argc&&JS_ToInt32(ctx,&n,argv[0])<0)return JS_EXCEPTION;if(n>0)particle_system_emit(w->system,(uint32_t)n);return JS_UNDEFINED;}
static JSValue set_transform(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv,int magic){JSParticle*w=get(ctx,self);if(!w)return JS_EXCEPTION;double a,b=0;if(!argc||JS_ToFloat64(ctx,&a,argv[0])<0||(magic==0&&(argc<2||JS_ToFloat64(ctx,&b,argv[1])<0)))return JS_ThrowTypeError(ctx,"numeric transform arguments required");if(magic==0){w->system->position_x=(float)a;w->system->position_y=(float)b;}else if(magic==1)w->system->rotation=(float)a;else w->system->scale=(float)a;return JS_UNDEFINED;}
static JSValue set_rate(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv){JSParticle*w=get(ctx,self);double n;if(!w)return JS_EXCEPTION;if(!argc||JS_ToFloat64(ctx,&n,argv[0])<0||n<0)return JS_ThrowRangeError(ctx,"emission rate must be non-negative");w->system->config.emission_rate=(float)n;return JS_UNDEFINED;}
static JSValue destroy(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv){(void)ctx;(void)argc;(void)argv;JSParticle*w=JS_GetOpaque(self,particle_class_id);if(w&&w->system){particle_system_destroy(w->system);w->system=NULL;}return JS_UNDEFINED;}
static void finalizer(JSRuntime*rt,JSValue value){JSParticle*w=JS_GetOpaque(value,particle_class_id);if(w){if(w->system)particle_system_destroy(w->system);js_free_rt(rt,w);}}
static const JSCFunctionListEntry methods[]={
 JS_CFUNC_MAGIC_DEF("start",0,noarg,0),JS_CFUNC_MAGIC_DEF("stop",0,noarg,1),JS_CFUNC_MAGIC_DEF("pause",0,noarg,2),JS_CFUNC_MAGIC_DEF("resume",0,noarg,3),
 JS_CFUNC_DEF("emit",1,emit),JS_CFUNC_MAGIC_DEF("setPosition",2,set_transform,0),JS_CFUNC_MAGIC_DEF("setRotation",1,set_transform,1),JS_CFUNC_MAGIC_DEF("setScale",1,set_transform,2),JS_CFUNC_DEF("setEmissionRate",1,set_rate),JS_CFUNC_DEF("destroy",0,destroy)};

static int parse_config(JSContext*ctx,JSValueConst o,ParticleConfig*c,char**texture,int*texture_id,int*texture_width,int*texture_height,float*threshold,float*softness,int*mask){
 particle_config_defaults(c);
 JSValue v=prop(ctx,o,"maxParticles");if(!JS_IsUndefined(v)){int32_t n;if(JS_ToInt32(ctx,&n,v)<0||n<1||n>1000000){JS_FreeValue(ctx,v);return -1;}c->max_particles=(uint32_t)n;}JS_FreeValue(ctx,v);
 v=prop(ctx,o,"seed");if(!JS_IsUndefined(v)){int32_t n;if(JS_ToInt32(ctx,&n,v)<0){JS_FreeValue(ctx,v);return -1;}c->seed=(uint32_t)n;}JS_FreeValue(ctx,v);
 if(string_is(ctx,o,"space","local"))c->space=PARTICLE_SPACE_LOCAL;else if(string_is(ctx,o,"space","world"))c->space=PARTICLE_SPACE_WORLD;
 v=prop(ctx,o,"area");if(JS_IsObject(v)){number(ctx,v,"x",&c->area_x);number(ctx,v,"y",&c->area_y);number(ctx,v,"width",&c->area_width);number(ctx,v,"height",&c->area_height);if(string_is(ctx,v,"boundary","wrap"))c->boundary=PARTICLE_BOUNDARY_WRAP;else if(string_is(ctx,v,"boundary","bounce"))c->boundary=PARTICLE_BOUNDARY_BOUNCE;else if(string_is(ctx,v,"boundary","kill"))c->boundary=PARTICLE_BOUNDARY_KILL;else if(string_is(ctx,v,"boundary","clamp"))c->boundary=PARTICLE_BOUNDARY_CLAMP;}JS_FreeValue(ctx,v);
 v=prop(ctx,o,"emission");if(JS_IsObject(v)){number(ctx,v,"rate",&c->emission_rate);boolean(ctx,v,"prewarm",&c->prewarm);}JS_FreeValue(ctx,v);
 v=prop(ctx,o,"spawn");if(JS_IsObject(v)){if(string_is(ctx,v,"shape","rect"))c->spawn_shape=PARTICLE_SPAWN_RECT;else if(string_is(ctx,v,"shape","circle"))c->spawn_shape=PARTICLE_SPAWN_CIRCLE;else if(string_is(ctx,v,"shape","area"))c->spawn_shape=PARTICLE_SPAWN_AREA;number(ctx,v,"width",&c->spawn_width);number(ctx,v,"height",&c->spawn_height);number(ctx,v,"radius",&c->spawn_radius);}JS_FreeValue(ctx,v);
 if(value_prop(ctx,o,"lifetime",&c->lifetime)<0||parse_size_prop(ctx,o,c)<0||value_prop(ctx,o,"opacity",&c->opacity)<0||value_prop(ctx,o,"rotation",&c->rotation)<0||value_prop(ctx,o,"angularVelocity",&c->angular_velocity)<0||value_prop(ctx,o,"speed",&c->speed)<0)return -1;
 v=prop(ctx,o,"velocity");if(JS_IsObject(v)&&(value_prop(ctx,v,"x",&c->velocity_x)<0||value_prop(ctx,v,"y",&c->velocity_y)<0)){JS_FreeValue(ctx,v);return -1;}JS_FreeValue(ctx,v);
 v=prop(ctx,o,"modifiers");if(JS_IsArray(ctx,v)){uint32_t n=0;array_length(ctx,v,&n);if(n>PARTICLE_MAX_MODIFIERS)n=PARTICLE_MAX_MODIFIERS;for(uint32_t i=0;i<n;i++){JSValue m=JS_GetPropertyUint32(ctx,v,i);if(!JS_IsObject(m)){JS_FreeValue(ctx,m);JS_FreeValue(ctx,v);return -1;}ParticleModifier*mod=&c->modifiers[c->modifier_count];memset(mod,0,sizeof(*mod));mod->strength.type=mod->frequency.type=PARTICLE_VALUE_CONSTANT;mod->strength.constant=1;mod->frequency.constant=1;if(string_is(ctx,m,"type","gravity")||string_is(ctx,m,"type","acceleration"))mod->type=PARTICLE_MOD_ACCELERATION;else if(string_is(ctx,m,"type","drag"))mod->type=PARTICLE_MOD_DRAG;else if(string_is(ctx,m,"type","oscillation"))mod->type=PARTICLE_MOD_OSCILLATION;else if(string_is(ctx,m,"type","noise"))mod->type=PARTICLE_MOD_NOISE;else{JS_FreeValue(ctx,m);JS_FreeValue(ctx,v);return -1;}number(ctx,m,"x",&mod->x);number(ctx,m,"y",&mod->y);if(mod->type==PARTICLE_MOD_OSCILLATION&&mod->x==0&&mod->y==0)mod->x=1;if(value_prop(ctx,m,"strength",&mod->strength)<0||value_prop(ctx,m,"frequency",&mod->frequency)<0){JS_FreeValue(ctx,m);JS_FreeValue(ctx,v);return -1;}c->modifier_count++;JS_FreeValue(ctx,m);}}JS_FreeValue(ctx,v);
 v=prop(ctx,o,"render");if(JS_IsObject(v)){JSValue t=prop(ctx,v,"texture");if(JS_IsString(t)){const char*s=JS_ToCString(ctx,t);if(s){size_t len=strlen(s);*texture=(char*)js_malloc(ctx,len+1);if(*texture)memcpy(*texture,s,len+1);JS_FreeCString(ctx,s);}}else if(JS_IsObject(t)){JSValue id=prop(ctx,t,"id"),w=prop(ctx,t,"widthPixels"),h=prop(ctx,t,"heightPixels");if(JS_ToInt32(ctx,texture_id,id)<0||JS_ToInt32(ctx,texture_width,w)<0||JS_ToInt32(ctx,texture_height,h)<0){JS_FreeValue(ctx,id);JS_FreeValue(ctx,w);JS_FreeValue(ctx,h);JS_FreeValue(ctx,t);JS_FreeValue(ctx,v);return -1;}JS_FreeValue(ctx,id);JS_FreeValue(ctx,w);JS_FreeValue(ctx,h);}JS_FreeValue(ctx,t);JSValue mk=prop(ctx,v,"mask");if(JS_IsObject(mk)&&string_is(ctx,mk,"source","directLight")){*mask=1;number(ctx,mk,"threshold",threshold);number(ctx,mk,"softness",softness);}JS_FreeValue(ctx,mk);}JS_FreeValue(ctx,v);
 return (*texture||(*texture_id>=0&&*texture_width>0&&*texture_height>0))?0:-1;
}

static JSValue create(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv){(void)self;if(!argc||!JS_IsObject(argv[0]))return JS_ThrowTypeError(ctx,"particles.create requires a config object");ParticleConfig c;char*texture=NULL;int texture_id=-1,texture_width=0,texture_height=0;float threshold=.05f,softness=.15f;int mask=0;if(parse_config(ctx,argv[0],&c,&texture,&texture_id,&texture_width,&texture_height,&threshold,&softness,&mask)<0){if(texture)js_free(ctx,texture);return JS_ThrowTypeError(ctx,"invalid particle configuration");}ParticleSystem*s=particle_system_create(&c);if(!s){if(texture)js_free(ctx,texture);return JS_ThrowOutOfMemory(ctx);}s->mask_direct_light=mask;s->mask_threshold=threshold;s->mask_softness=softness;if(texture_id>=0){s->texture_id=texture_id;s->texture_width=texture_width;s->texture_height=texture_height;}JSParticle*w=js_mallocz(ctx,sizeof(*w));if(!w){particle_system_destroy(s);if(texture)js_free(ctx,texture);return JS_ThrowOutOfMemory(ctx);}w->system=s;JSValue obj=JS_NewObjectClass(ctx,particle_class_id);if(JS_IsException(obj)){particle_system_destroy(s);js_free(ctx,w);if(texture)js_free(ctx,texture);return obj;}JS_SetOpaque(obj,w);if(texture){engine_request_particle_texture(texture,s->id);js_free(ctx,texture);}return obj;}

JSValue particle_js_create_api(JSContext*ctx){if(!particle_class_ready){JS_NewClassID(&particle_class_id);JSClassDef def={"ParticleSystem",.finalizer=finalizer};if(JS_NewClass(JS_GetRuntime(ctx),particle_class_id,&def)<0)return JS_EXCEPTION;JSValue proto=JS_NewObject(ctx);JS_SetPropertyFunctionList(ctx,proto,methods,sizeof(methods)/sizeof(methods[0]));JS_SetClassProto(ctx,particle_class_id,proto);particle_class_ready=1;}JSValue api=JS_NewObject(ctx);JS_SetPropertyStr(ctx,api,"create",JS_NewCFunction(ctx,create,"create",1));return api;}
void particle_js_shutdown(void){particle_system_shutdown_all();}
