#!/usr/bin/env python
"""fips main entry"""
import os
import sys
import subprocess

proj_path = os.path.dirname(os.path.abspath(__file__))
fips_path = os.path.dirname(proj_path) + '/fips'
if not os.path.isfile(os.path.join(fips_path, 'cmake', 'fips.cmake')):
    print("\033[93m=== cloning fips build system to '{}':\033[0m".format(fips_path))
    subprocess.call(['git', 'clone', 'https://github.com/floooh/fips.git', fips_path])

# Keep this older fips revision working on Python versions where distutils and
# the collections.Hashable alias have been removed.
if sys.version_info[0] >= 3:
    import collections
    import collections.abc
    import shutil
    import types
    collections.Hashable = collections.abc.Hashable
    if 'distutils.spawn' not in sys.modules:
        distutils_module = types.ModuleType('distutils')
        spawn_module = types.ModuleType('distutils.spawn')
        spawn_module.find_executable = shutil.which
        distutils_module.spawn = spawn_module
        sys.modules['distutils'] = distutils_module
        sys.modules['distutils.spawn'] = spawn_module

def normalize_emsdk_config():
    """Expand modern emsdk's $CFGDIR for the older fips config parser."""
    config_path = os.path.join(os.path.dirname(fips_path), 'fips-sdks', 'emsdk', '.emscripten')
    if os.path.isfile(config_path):
        with open(config_path, 'r') as config_file:
            contents = config_file.read()
        expanded = contents.replace('$CFGDIR', os.path.dirname(config_path))
        if expanded != contents:
            with open(config_path, 'w') as config_file:
                config_file.write(expanded)

normalize_emsdk_config()
sys.path.insert(0, fips_path)
try:
    from mod import fips
except ImportError:
    print("\033[91m[ERROR]\033[0m failed to initialize fips build system in '{}'".format(proj_path))
    sys.exit(10)
fips.run(fips_path, proj_path, sys.argv)
normalize_emsdk_config()
